name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true

env:
  GITHUB_TOKEN:          ${{ secrets.GITHUB_TOKEN }}
  RELEASE_VERSION:       ${{ github.event.inputs.release }}
  REF_TYPE:              ${{ github.ref_type }}
  OWNER:                 ${{ github.repository_owner }}
  REPO_NAME:             ${{ github.event.repository.name }}
  CACHE_NAME:            'npm-cache'
  RED:                   '\033[1;91m'
  GREEN:                 '\033[1;92m'
  BLUE:                  '\033[1;94m'
  NC:                    '\033[0m'

jobs:
  release:
    name: 🏷 Release
    runs-on: ubuntu-latest
    outputs:
      ssr: ${{ steps.set_ssr.outputs.ssr }}

    steps:
      - name: Exit if is not a branch
        if: env.REF_TYPE != 'branch'
        run: |
          echo -e "${{ env.RED }}[Error] ${{ env.NC }}You must select a branch not a tag"
          exit 1
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}
      - name: 🔨 Build
        run: |
          npm ci
          npm run build
      - name: 📦 Compress dist
        run: |
          zip -r dist.zip ./dist
      - name: 🏷 Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ env.RELEASE_VERSION }}',
              sha: context.sha
            })
      - name: 🏷 Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
      - name: ⬆️  Upload dist
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
